anidb:
    server: api.anidb.net
    port: 9000
    remoteport: 9001
    username: username
    password: password
    nat: true

renamer:
    animebase: /mnt/fileshare/video/Anime
    moviebase: /mnt/fileshare/video/Anime OVA
    unsorted: /mnt/fileshare/video/Anime Unsorted

# This is ActiveRecord syntax, supports anything he does.
# Note that db/*.sqlite3 is excluded from git, so you should use that
# naming pattern when you are saving your sqlite database to this folder
database:
    adapter: sqlite3
    database: db/database.sqlite3

logging:
    level: info

    destinations:
#    - file: /Users/ubercow/Desktop/coolguy.log
    - gelf:
        host: ledo
        port: 12201

transmission:
    url: http://transmission:9091/transmission/rpc
    username: transmission
    password: password

# If this isn't specified, radionoise won't add to the backlog
radionoise:
    backlog: 3 days from now
